#!/bin/bash

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i $ssh_key $/root/.ssh/id_rsa $5fc8bbf7d1d3@$5fc8bbf7d1d3.11e6984a.alx-cod.online:~/

