#!/usr/bin/env bash
# Install Nginx

apt-get update
apt-get install -y nginx

# Configure Nginx to listen on port 80
echo "server {
    listen 80;
    server_name _;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
service nginx restart

# Verify Nginx status
curl localhost

