#!/usr/bin/env bash
# This is a script that Creates the file /var/run/myscript.pid containing its PID, Displays To infinity and beyond indefinitely, Displays I hate the kill command when receiving a SIGTERM signal

cleanup() {
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit
}

handle_sigint() {
	echo "Y U no love me?!"
}

handle_sigterm() {
	echo "I hate the kill command"
}

sudo touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
	trap 'cleanup' SIGQUIT SIGTERM
	trap 'handle_sigint' SIGINT
	sleep 2
done
