#!/usr/bin/env bash

cleanup() {
	echo "Deleting PID file and terminating..."
	rm -f /var/run/myscript.pid
	exit
}

handle_sigint() {
	echo "Y U no love me?!"
}

handle_sigterm() {
	echo "I hate the kill command"
}

trap 'cleanup' SIGQUIT SIGTERM
trap 'handle_sigint' SIGINT

echo $$ > /var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
	sleep 2
done
