#!/usr/bin/env bash

process_dir="/proc/[0-9]*"

for pid_dir in $process_dir; do
	pid=$(basename "$pid_dir")
	if [[ -f "$pid_dir/cmdline" ]]; then
		process_name=$(tr '\0' ' ' < "$pid_dir/cmdline" | awk '{print $1}')
		if [[ "$process_name" == *"bash"* ]]; then
			echo "$pid $process_name"
		fi
        fi
done
