#!/usr/bin/env bash
# This is a script that stops 4-to_infinity_and_beyond process.

pid=$(pgrep -f "4-to_inifinity_and_beyond")

if [ -n "$pid" ]; then
	echo "Sending SINGNT signal to process $pid"
	kill -SIGINT "$pid"
	echo "Terminated"
else
	echo "Process not found"
fi
