#!/usr/bin/env bash
# This is a script that, Indefinitely writes I am alive! to the file /tmp/my_process, In between every I am alive! message, the program should pause for 2 seconds

case $1 in
	start)
		./manage_my_process & echo $! > /var/run/my_process.pid
		echo "manage_my_process start"
		;;
	stop)
		kill $(cat /var/run/my_process.pid)
		rm /var/rum/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		$0 stop
		$0 start
		echo "manage_my_process restart"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac
