#!/usr/bin/env bash
# This is a script that displays the content of the file /etc/passwd

FILENAME="/etc/passwd"

while IFS=: read -r username userid homedir
do
	echo "$username:$userid:$homedir"
done < "$FILENAME"
