#!/usr/bin/env bash
# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# Create an Nginx configuration file
cat <<EOF > /etc/nginx/sites-available/my_nginx_config
server {
    listen 8080;
    server_name _;  # Listen on all active IPs

    location / {
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header Host \$http_host;
        proxy_pass http://127.0.0.1:8080;  # Forward requests to your application
    }
}
EOF

sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf

# Enable the configuration
ln -s /etc/nginx/sites-available/my_nginx_config /etc/nginx/sites-enabled/
service nginx restart

