#!/usr/bin/env bash
apt-get update
apt-get install -y nginx
echo -e "server {\n    listen 8080;\n    server_name _;\n\n    location / {\n        proxy_set_header X-Forwarded-For \$remote_addr;\n        proxy_set_header Host \$http_host;\n        proxy_pass http://127.0.0.1:8080;\n    }\n}" > /etc/nginx/sites-available/my_nginx_config
ln -s /etc/nginx/sites-available/my_nginx_config /etc/nginx/sites-enabled/
service nginx restart

