#!/usr/bin/env bash
# This Bash script that uses ssh to connect to your server
# using the private key ~/.ssh/school with the user ubuntu

ssh -i ~/.ssh/school ubuntu@d3c4fa12543d.ae4d45e0.alx-cod.online
