#!/usr/bin/env bash

# Generate an RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f school -N "betty"

# Display success message
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in school."
echo "Your public key has been saved in school.pub."
